[package]
name = "washer"
version = "0.1.0"
authors = ["Mark Ellis <m@rkellis.com>"]
edition = "2018"

[dependencies]
select = "0.5"
reqwest = "0.11"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
